List<String> koenige_england = [
  'Alfred der Große',
  'Eduard der Ältere',
  'Athelstan',
  'Edmund der Ältere',
  'Eadred',
  'Eadwig',
  'Edgar der Friedfertige',
  'Eduard der Märtyrer',
  'Ethelred der Unberatene',
  'Sven Gabelbart',
  'Ethelred der Unberatene',
  'Edmund II.',
  'Knut der Große',
  'Harald I. Harefoot',
  'Hardekanut',
  'Eduard der Bekenner',
  'Harold II.',
  'Edgar der Ätheling',
  'Wilhelm der Eroberer',
  'Wilhelm II.',
  'Heinrich I.',
  'Stephan',
  'Heinrich II.',
  'Richard I.',
  'Johann Ohneland',
  'Heinrich III.',
  'Eduard I.',
  'Eduard II.',
  'Eduard III.',
  'Richard II.',
  'Heinrich IV.',
  'Heinrich V.',
  'Heinrich VI.',
  'Eduard IV.',
  'Eduard V.',
  'Richard III.',
  'Heinrich VII.',
  'Heinrich VIII.',
  'Eduard VI.',
  'Jane Grey',
  'Maria I.',
  'Elisabeth I.',
  'Jakob I.',
  'Karl I.',
  'Oliver Cromwell',
  'Richard Cromwell',
  'Karl II.',
  'Jakob II.',
  'Wilhelm III.',
  'Maria II.',
  'Anna',
  'Georg I.',
  'Georg II.',
  'Georg III.',
  'Georg IV.',
  'Wilhelm IV.',
  'Victoria',
  'Eduard VII.',
  'Georg V.',
  'Eduard VIII.',
  'Georg VI.',
  'Elisabeth II.',
  'Charles III.'
];
