  // List<String> praesidenten = [
  //   'George Washington',
  //   'John Adams',
  //   'Thomas Jefferson',
  //   'James Madison',
  //   'James Monroe',
  //   'John Quincy Adams',
  //   'Andrew Jackson',
  //   'Martin Van Buren',
  //   'William Henry Harrison',
  //   'John Tyler',
  //   'James K. Polk',
  //   'Zachary Taylor',
  //   'Millard Fillmore',
  //   'Franklin Pierce',
  //   'James Buchanan',
  //   'Abraham Lincoln',
  //   'Andrew Johnson',
  //   'Ulysses S. Grant',
  //   'Rutherford B. Hayes',
  //   'James A. Garfield',
  //   'Chester A. Arthur',
  //   'Grover Cleveland',
  //   'Benjamin Harrison',
  //   'Grover Cleveland',
  //   'William McKinley',
  //   'Theodore Roosevelt',
  //   'William Howard Taft',
  //   'Woodrow Wilson',
  //   'Warren G. Harding',
  //   'Calvin Coolidge',
  //   'Herbert Hoover',
  //   'Franklin D. Roosevelt',
  //   'Harry S. Truman',
  //   'Dwight D. Eisenhower',
  //   'John F. Kennedy',
  //   'Lyndon B. Johnson',
  //   'Richard Nixon',
  //   'Gerald Ford',
  //   'Jimmy Carter',
  //   'Ronald Reagan',
  //   'George H. W. Bush',
  //   'Bill Clinton',
  //   'George W. Bush',
  //   'Barack Obama',
  //   'Donald Trump',
  //   'Joe Biden',
  // ];

List<Map<String, String>> praesidenten = [
{'name': 'George Washington', 'amtsdauer': '1789-1797'},
{'name': 'John Adams', 'amtsdauer': '1797-1801'},
{'name': 'Thomas Jefferson', 'amtsdauer': '1801-1809'},
{'name': 'James Madison', 'amtsdauer': '1809-1817'},
{'name': 'James Monroe', 'amtsdauer': '1817-1825'},
{'name': 'John Quincy Adams', 'amtsdauer': '1825-1829'},
{'name': 'Andrew Jackson', 'amtsdauer': '1829-1837'},
{'name': 'Martin Van Buren', 'amtsdauer': '1837-1841'},
{'name': 'William Henry Harrison', 'amtsdauer': '1841'},
{'name': 'John Tyler', 'amtsdauer': '1841-1845'},
{'name': 'James K. Polk', 'amtsdauer': '1845-1849'},
{'name': 'Zachary Taylor', 'amtsdauer': '1849-1850'},
{'name': 'Millard Fillmore', 'amtsdauer': '1850-1853'},
{'name': 'Franklin Pierce', 'amtsdauer': '1853-1857'},
{'name': 'James Buchanan', 'amtsdauer': '1857-1861'},
{'name': 'Abraham Lincoln', 'amtsdauer': '1861-1865'},
{'name': 'Andrew Johnson', 'amtsdauer': '1865-1869'},
{'name': 'Ulysses S. Grant', 'amtsdauer': '1869-1877'},
{'name': 'Rutherford B. Hayes', 'amtsdauer': '1877-1881'},
{'name': 'James A. Garfield', 'amtsdauer': '1881'},
{'name': 'Chester A. Arthur', 'amtsdauer': '1881-1885'},
{'name': 'Grover Cleveland', 'amtsdauer': '1885-1889'},
{'name': 'Benjamin Harrison', 'amtsdauer': '1889-1893'},
{'name': 'Grover Cleveland', 'amtsdauer': '1893-1897'},
{'name': 'William McKinley', 'amtsdauer': '1897-1901'},
{'name': 'Theodore Roosevelt', 'amtsdauer': '1901-1909'},
{'name': 'William Howard Taft', 'amtsdauer': '1909-1913'},
{'name': 'Woodrow Wilson', 'amtsdauer': '1913-1921'},
{'name': 'Warren G. Harding', 'amtsdauer': '1921-1923'},
{'name': 'Calvin Coolidge', 'amtsdauer': '1923-1929'},
{'name': 'Herbert Hoover', 'amtsdauer': '1929-1933'},
{'name': 'Franklin D. Roosevelt', 'amtsdauer': '1933-1945'},
{'name': 'Harry S. Truman', 'amtsdauer': '1945-1953'},
{'name': 'Dwight D. Eisenhower', 'amtsdauer': '1953-1961'},
{'name': 'John F. Kennedy', 'amtsdauer': '1961-1963'},
{'name': 'Lyndon B. Johnson', 'amtsdauer': '1963-1969'},
{'name': 'Richard Nixon', 'amtsdauer': '1969-1974'},
{'name': 'Gerald Ford', 'amtsdauer': '1974-1977'},
{'name': 'Jimmy Carter', 'amtsdauer': '1977-1981'},
{'name': 'Ronald Reagan', 'amtsdauer': '1981-1989'},
{'name': 'George H. W. Bush', 'amtsdauer': '1989-1993'},
{'name': 'Bill Clinton', 'amtsdauer': '1993-2001'},
{'name': 'George W. Bush', 'amtsdauer': '2001-2009'},
{'name': 'Barack Obama', 'amtsdauer': '2009-2017'},
{'name': 'Donald Trump', 'amtsdauer': '2017-2021'},
{'name': 'Joe Biden', 'amtsdauer': '2021-present'},
];